#
# Application Core Image
#

# Pull base image
FROM busybox

MAINTAINER Serghei Iakovlev <serghei@phalconphp.com>

RUN mkdir /var/www/forum
WORKDIR /var/www/forum

# Expose volumes
VOLUME ["/var/www/forum"]
